version: '2'

services:
  influx:
    image: influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
    expose:
      - 8086
    volumes:
      - ./influxdb:/var/lib/influxdb
      - ./influxdb_etc:/etc/influxdb
    environment:
      - PGID=1000
      - PUID=1000
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin

  grafana:
    image: grafana/grafana
    ports:
      - "4242:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    user: 'root'
