version: '2'

services:
  influx:
    image: influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
    volumes:
      - ./influxdb:/var/lib/influxdb
      - ./influxdb_etc:/etc/influxdb
  grafana:
    image: grafana/grafana
    ports:
      - "4242:3000"
    volumes:
      - ./grafana:/var/lib/grafana
