version: '2'

services:
  influx:
    image: influxdb:alpine
    ports:
      - "8086:8086"
      - "8083:8083"
    volumes:
      - ./influxdb:/var/lib/influxdb
      - ./influxdb_etc:/etc/influxdb/
    environment:
      - INFLUXDB_DB=planty
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
  grafana:
    image: grafana/grafana
    ports:
      - "4242:3000"
    volumes:
      - ./grafana:/var/lib/grafana
